[package]
name = "mi-parsing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-openai = "0.10.1"
color-eyre = "0.6.2"
eyre = "0.6.8"
futures = "0.3.27"
glob = "0.3.1"
tokio = { version = "1.26.0", features = ["full"] }
